version: '2'

services:

  user:
    image: user
    build: ./user-rs
    container_name: user_app
    ports:
       - "9090:8080"
    networks:
      main:
        aliases:
          - user

  message:
    image: message
    build: ./message-rs
    container_name: message_app
    depends_on:
       - user
    ports:
       - "10000:8080"
    networks:
      main:
        aliases:
          - message

  chat:
    image: chat
    build: ./chat-rs
    container_name: chat_app
    ports:
       - "8080:8080"
    depends_on:
       - user
       - message
    networks:
      main:
        aliases:
          - chat

networks:
  main:
    driver: bridge
