
package task.monitor.server.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MonitorService", targetNamespace = "http://service.server.monitor.task/", wsdlLocation = "file:/media/juan/DATA/linux/sistemas-distribuidos/lista_sd_COLABORATIVA/questao01/client/src/main/java/monitor.wsdl")
public class MonitorService
    extends Service
{

    private final static URL MONITORSERVICE_WSDL_LOCATION;
    private final static WebServiceException MONITORSERVICE_EXCEPTION;
    private final static QName MONITORSERVICE_QNAME = new QName("http://service.server.monitor.task/", "MonitorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/media/juan/DATA/linux/sistemas-distribuidos/lista_sd_COLABORATIVA/questao01/client/src/main/java/monitor.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MONITORSERVICE_WSDL_LOCATION = url;
        MONITORSERVICE_EXCEPTION = e;
    }

    public MonitorService() {
        super(__getWsdlLocation(), MONITORSERVICE_QNAME);
    }

    public MonitorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MONITORSERVICE_QNAME, features);
    }

    public MonitorService(URL wsdlLocation) {
        super(wsdlLocation, MONITORSERVICE_QNAME);
    }

    public MonitorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MONITORSERVICE_QNAME, features);
    }

    public MonitorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonitorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Monitor
     */
    @WebEndpoint(name = "MonitorServicePort")
    public Monitor getMonitorServicePort() {
        return super.getPort(new QName("http://service.server.monitor.task/", "MonitorServicePort"), Monitor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Monitor
     */
    @WebEndpoint(name = "MonitorServicePort")
    public Monitor getMonitorServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.server.monitor.task/", "MonitorServicePort"), Monitor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MONITORSERVICE_EXCEPTION!= null) {
            throw MONITORSERVICE_EXCEPTION;
        }
        return MONITORSERVICE_WSDL_LOCATION;
    }

}
