
package task.monitor.server.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Monitor", targetNamespace = "http://service.server.monitor.task/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Monitor {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registry", targetNamespace = "http://service.server.monitor.task/", className = "task.monitor.server.service.Registry")
    @ResponseWrapper(localName = "registryResponse", targetNamespace = "http://service.server.monitor.task/", className = "task.monitor.server.service.RegistryResponse")
    @Action(input = "http://service.server.monitor.task/Monitor/registryRequest", output = "http://service.server.monitor.task/Monitor/registryResponse")
    public void registry(
        @WebParam(name = "arg0", targetNamespace = "")
        TaskEvent arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<task.monitor.server.service.TaskEvent>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://service.server.monitor.task/", className = "task.monitor.server.service.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://service.server.monitor.task/", className = "task.monitor.server.service.ListResponse")
    @Action(input = "http://service.server.monitor.task/Monitor/listRequest", output = "http://service.server.monitor.task/Monitor/listResponse")
    public List<TaskEvent> list(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
