
package ws.user.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSUserService", targetNamespace = "http://service.user.ws/", wsdlLocation = "file:/media/juan/DATA/linux/questao03/wschat/src/main/java/user.wsdl")
public class WSUserService
    extends Service
{

    private final static URL WSUSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSUSERSERVICE_EXCEPTION;
    private final static QName WSUSERSERVICE_QNAME = new QName("http://service.user.ws/", "WSUserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/media/juan/DATA/linux/questao03/wschat/src/main/java/user.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSUSERSERVICE_WSDL_LOCATION = url;
        WSUSERSERVICE_EXCEPTION = e;
    }

    public WSUserService() {
        super(__getWsdlLocation(), WSUSERSERVICE_QNAME);
    }

    public WSUserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSUSERSERVICE_QNAME, features);
    }

    public WSUserService(URL wsdlLocation) {
        super(wsdlLocation, WSUSERSERVICE_QNAME);
    }

    public WSUserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSUSERSERVICE_QNAME, features);
    }

    public WSUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSUserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSUser
     */
    @WebEndpoint(name = "WSUserImplPort")
    public WSUser getWSUserImplPort() {
        return super.getPort(new QName("http://service.user.ws/", "WSUserImplPort"), WSUser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSUser
     */
    @WebEndpoint(name = "WSUserImplPort")
    public WSUser getWSUserImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.user.ws/", "WSUserImplPort"), WSUser.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSUSERSERVICE_EXCEPTION!= null) {
            throw WSUSERSERVICE_EXCEPTION;
        }
        return WSUSERSERVICE_WSDL_LOCATION;
    }

}
