
package ws.message.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSMessage", targetNamespace = "http://service.message.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSMessage {


    /**
     * 
     * @return
     *     returns java.util.List<ws.message.service.Message>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://service.message.ws/", className = "ws.message.service.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://service.message.ws/", className = "ws.message.service.ListResponse")
    @Action(input = "http://service.message.ws/WSMessage/listRequest", output = "http://service.message.ws/WSMessage/listResponse")
    public List<Message> list();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "store", targetNamespace = "http://service.message.ws/", className = "ws.message.service.Store")
    @ResponseWrapper(localName = "storeResponse", targetNamespace = "http://service.message.ws/", className = "ws.message.service.StoreResponse")
    @Action(input = "http://service.message.ws/WSMessage/storeRequest", output = "http://service.message.ws/WSMessage/storeResponse")
    public boolean store(
        @WebParam(name = "arg0", targetNamespace = "")
        Message arg0);

}
