
package ws.message.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSMessageService", targetNamespace = "http://service.message.ws/", wsdlLocation = "file:/media/juan/DATA/linux/sistemas-distribuidos/lista_sd_COLABORATIVA/questao03/wschat/src/main/java/message.wsdl")
public class WSMessageService
    extends Service
{

    private final static URL WSMESSAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException WSMESSAGESERVICE_EXCEPTION;
    private final static QName WSMESSAGESERVICE_QNAME = new QName("http://service.message.ws/", "WSMessageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/media/juan/DATA/linux/sistemas-distribuidos/lista_sd_COLABORATIVA/questao03/wschat/src/main/java/message.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSMESSAGESERVICE_WSDL_LOCATION = url;
        WSMESSAGESERVICE_EXCEPTION = e;
    }

    public WSMessageService() {
        super(__getWsdlLocation(), WSMESSAGESERVICE_QNAME);
    }

    public WSMessageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSMESSAGESERVICE_QNAME, features);
    }

    public WSMessageService(URL wsdlLocation) {
        super(wsdlLocation, WSMESSAGESERVICE_QNAME);
    }

    public WSMessageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSMESSAGESERVICE_QNAME, features);
    }

    public WSMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSMessageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSMessage
     */
    @WebEndpoint(name = "WSMessageImplPort")
    public WSMessage getWSMessageImplPort() {
        return super.getPort(new QName("http://service.message.ws/", "WSMessageImplPort"), WSMessage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSMessage
     */
    @WebEndpoint(name = "WSMessageImplPort")
    public WSMessage getWSMessageImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.message.ws/", "WSMessageImplPort"), WSMessage.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSMESSAGESERVICE_EXCEPTION!= null) {
            throw WSMESSAGESERVICE_EXCEPTION;
        }
        return WSMESSAGESERVICE_WSDL_LOCATION;
    }

}
