
package ws.chat.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSChatService", targetNamespace = "http://service.chat.ws/", wsdlLocation = "file:/media/juan/DATA/linux/sistemas-distribuidos/lista_sd_COLABORATIVA/questao03/client/src/main/java/chat.wsdl")
public class WSChatService
    extends Service
{

    private final static URL WSCHATSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSCHATSERVICE_EXCEPTION;
    private final static QName WSCHATSERVICE_QNAME = new QName("http://service.chat.ws/", "WSChatService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/media/juan/DATA/linux/sistemas-distribuidos/lista_sd_COLABORATIVA/questao03/client/src/main/java/chat.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCHATSERVICE_WSDL_LOCATION = url;
        WSCHATSERVICE_EXCEPTION = e;
    }

    public WSChatService() {
        super(__getWsdlLocation(), WSCHATSERVICE_QNAME);
    }

    public WSChatService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCHATSERVICE_QNAME, features);
    }

    public WSChatService(URL wsdlLocation) {
        super(wsdlLocation, WSCHATSERVICE_QNAME);
    }

    public WSChatService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCHATSERVICE_QNAME, features);
    }

    public WSChatService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSChatService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSChat
     */
    @WebEndpoint(name = "WSChatImplPort")
    public WSChat getWSChatImplPort() {
        return super.getPort(new QName("http://service.chat.ws/", "WSChatImplPort"), WSChat.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSChat
     */
    @WebEndpoint(name = "WSChatImplPort")
    public WSChat getWSChatImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.chat.ws/", "WSChatImplPort"), WSChat.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCHATSERVICE_EXCEPTION!= null) {
            throw WSCHATSERVICE_EXCEPTION;
        }
        return WSCHATSERVICE_WSDL_LOCATION;
    }

}
